mylist = ["java","Python",99,24,4.3]
mylist1 = ["Riddhi",34,"Class"]
mylist2 = [37,45,21,70,84]

mylist2.sort()
print(mylist2)
mylist1.reverse()
print(mylist1)
print(sorted(mylist2))
print(max(mylist2))
print(min(mylist2))
print(sum(mylist2))
mycount= mylist.count("python")
print(mycount)
mycount= mylist.append("hello")
print(mylist)
mylist1.insert(2,"byy")
print(mylist1)
position=mylist.index("java")
print(position)
mylist.pop(2)
print(mylist)
mylist2.remove(37)
print(mylist2)
newlist= mylist.copy()
print(newlist)
mylist1.extend(mylist2)
print(mylist1)
mylist2.clear()
print(mylist2)